### ISSUE TITLE
Public NuGet package

### ISSUE THREAD

**Issue by rs22** [patagonaa/CoAP.Net#13]
Thanks for sharing these updates to the original library!

Would you consider uploading the tagged versions to a NuGet registry (maybe Nuget.org or GitHub) to make it easier to reference your fork?

I'm using the Dtls implementation and have used the updated BouncyCastle version to perform X509 certificate-based client authentication.

**Comment by patagonaa** [comment]
Sure, I can do that.

Sorry for not answering earlier, GitHub doesn't appear to automatically watch forks, so I didn't get a notification.

I'll probably do it today if I don't forget.

**Comment by patagonaa** [comment]
It is released now: https://www.nuget.org/packages/patagona.CoAPNet/ (also the corresponding Server, Dtls and Udp packages).

Let me know if you encounter any issues (also, be aware I changed some namespaces recently so it might not be a drop-in replacement)

**Comment by rs22** [comment]
Thanks! Everything seems to work as before for me.
